version: "3"

services: 

  scheduler-app:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: scheduler-app
    env_file: .env
    networks: 
      - default
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/github.com/Blackmocca/go-lightweight-scheduler

  scheduler-app-2:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: scheduler-app-2
    env_file: .env
    networks: 
      - default
    ports:
      - 3002:3000
    volumes:
      - .:/go/src/github.com/Blackmocca/go-lightweight-scheduler

  scheduler-app-3:
    build:
      context: ./
      dockerfile: ./Dockerfile-development
    container_name: scheduler-app-3
    env_file: .env
    networks: 
      - default
    ports:
      - 3003:3000
    volumes:
      - .:/go/src/github.com/Blackmocca/go-lightweight-scheduler

  scheduler-pg-db:
    image: postgres:15
    container_name: scheduler-pg-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=scheduler
    networks: 
      - default
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/var/lib/postgresql/data

  scheduler-adminer:
    image: adminer
    container_name: scheduler-adminer
    networks: 
      - default
    ports:
      - 8088:8080

networks:
  default:
    external:
      name: scheduler